### ISSUE TITLE
Better furigana support for the word - anki field 

### ISSUE THREAD

**Issue by gattigcg1** [rampaa/JL#103]
For example for 身の上:

It would be great to have a field that would generate something like: 身[み]の 上[うえ] , which would generate nice furigana as below:

![image](https://github.com/user-attachments/assets/45cd542c-0b05-4f54-b240-0832b0d2487f)

If it's like 身の上[みのうえ], it would look like this: 

![image](https://github.com/user-attachments/assets/a6a5ac72-3ea7-4313-8ffc-b533cd6cb698)

The space helps (の 上[うえ]) so that the furigana doesn't go on top of の as well in certain situations.

**Comment by rampaa** [comment]
In order to do this, I'd either need to add a dependency to something like https://github.com/Doublevil/JmdictFurigana (which would only cover the words found in JMdict) or I'd need to load a kanji dictionary and try to generate the desired furigana on-the-fly by using that dictionary as well (which I am not confident I can pull off with 100% accuracy). Unless I find a more reliable way of of generating this data, I am not willing to implement this feature, sorry.

**Comment by rampaa** [comment]
I've realized you were probably just asking a better handling for primary spellings that contain kana instead of proper furigana generation. So while JL won't be generating `頑[がん]張[ば]り` for the aforementioned reasons, it will now generate `頑張[がんば]り`. It probably can be made better, so PRs are welcome.
