### ISSUE TITLE
Mark Duplicates in Lookups/Mining Dialogue

### ISSUE THREAD

**Issue by bpwhelan** [rampaa/JL#107]
This would be a useful feature to have similar to Yomitan's implementation for a few reasons. I feel duplicate cards are useful for some words that require a lot of different context to really undersand. Few other reasons..

- Just knowing that you've added a card can give you some insight on how important that word is to you.
- Mining with "Allow Duplicates" would become a lot more useful, as of right now you just mine the card and you won't know it's a duplicate until you take a look at the card or have some kind of way of notifying you that there is a duplicate.

I might look at adding this and PRing, since it would be super helpful for my setup, but no promises.

**Comment by rampaa** [comment]
I am not familiar with how Yomitan is displaying that information, including that detail would make it easier for me to visualize exactly what is being asked here.

Regardless, here are a few things to keep in mind if you intend to create a PR for this:

1) Users who don't wish to use it (including me, since I don't mine at all) shouldn't have to pay for it. In other words, the existence of this feature shouldn't make lookups any slower for users who don't wish to use it.
2) Even for users who choose to opt into using it, its performance impact should be minimal. If a user has lots of dictionaries and happens to look up a word written in kana, JL might list _lots of_ results. If you want this information to be shown for all results without any interaction, its performance impact might not be acceptable. Of course, this may depend on whether Anki Connect allows us to fetch the required information in batches, etc. However, if such an approach proves to have an unacceptable performance impact, then a different approach should be taken, such as requiring a button press on a specific result to show whether it's a duplicate.

I probably won't be implementing this feature myself because I don't personally have a use for it, and its performance characteristics might not be acceptable. So, if you decide not to make a PR for it, feel free to close this issue.

**Comment by bpwhelan** [comment]
Sure, 
![image](https://github.com/user-attachments/assets/53f2b3b6-6dc0-43d7-a2ec-de54f730770d)

Here is how Yomitan displays it. It also allows you to open the anki note with the button to the left of that (the book), which would also be nice to have, but I don't want to add any buttons, JL seems to be more focused on playing rather than mining, which i totally agree with.

This will likely just end up being an icon somewhere along this line with a hover over to show a tooltip saying there already exists a card in the deck configured. This would only be processed/shown when the "mining" button is clicked, so there is no impact whatsoever to normal lookups. 

![image](https://github.com/user-attachments/assets/25bed449-1084-456a-8942-6229cb6f1a3d)

Just theoretically speaking the performance impact should be minimal, but I will have to test some to know concretely.

**Comment by bpwhelan** [comment]
![image](https://github.com/user-attachments/assets/834efdcc-c407-415e-8371-1854a6d7250b)

By no means is done, but seems to be mostly working with what I slapped in there. If you have any general design asks let me know.

**Comment by rampaa** [comment]
> This would only be processed/shown when the "mining" button is clicked

Do you mean it would only be shown when you click on the primary spelling that allows you to mine the word (e.g., 屋 written in orange in your screenshot)? Or do you mean it would only be shown when the "Mining mode" button/hotkey (e.g., middle mouse button/Alt+M), that enables the mining mode, is pressed?

If you mean the former, then what's the plan exactly? Currently, when you click on the primary spelling JL will try to mine it and will close the popup regardless of the success of the operation. If there was an error it will be shown as an "alert" in the upper right side of your screen and if it was a success. Do you want the popup to remain open if the card you try to create is a duplicate to show the "it's a duplicate" icon? Would an alert like "Mined duplicated card" suffice in that case?

If you mean the latter, I am afraid it does count as a normal lookup because `Mouse click/Touch` and `Text select` lookup modes do enable mining mode by default and especially `Mouse click/Touch` _is_ being used by many people.

**Comment by rampaa** [comment]
> If you have any general design asks let me know

1) Go with a design that would have the least impact on the performance.

    For example, showing an alert like "Mined {Primary Spelling} (Duplicate)" after we mine the term would be pretty trivial and it would have basically zero performance overhead. Asking "This card is a duplicate, are you really sure you want to mine it anyway?" after user clicks on the primary spelling would also have basically zero performance overhead. If any of these designs would suffice for your use-case, please prefer them over checking the duplicate-ness of every result in mining mode.

    If the abovementioned approaches wouldn't be useful for your use-case and you need to see the duplicate-ness of every result in mining mode with a glance, then make create an option to enable this feature and make the default value of that option false. I'd also appricate it if you can test this feature's performance impact with lots of dictionaries.

2) JL allows users to mine to a text file as well but we probably shouldn't check the content of the file to detect if the result we are trying to mine is a duplicate or not. So the duplication check should only be done if `Preferences -> Advanced -> Mine to file instead of Anki` is disabled.

3) Make sure your code doesn't introduce a new warning/suggestion in Visual Studio/Rider.

**Comment by bpwhelan** [comment]
I have the latter implemented currently, i did think about just changing the notification to show that it's a duplicate, but for me there is still useful information in the mining screen that would come from checking "everything" for duplicates.

Simple example, if i have an existing card for 目標 and the word is 目標的, that might influence my decision to mine 目標的 (like, i absolutely don't need a card)

I will check out what you mentioned about left click counting as mining mode when i get home, all my logic is hidden under if miningmode as of right now, but i just threw it in there without much care just for my personal use.
