### ISSUE TITLE
Any posibility of using magpie and JL together?

### ISSUE THREAD

**Issue by yourmom2002** [rampaa/JL#21]
https://github.com/Blinue/Magpie makes possible to use neural upscalers like anime4k for eroge, but i can't put JL window on top of fullscreen created by magpie. 
Is there any chance to use them together? Maybe i should ask this in magpie github issues instead?

**Comment by rampaa** [comment]
> Maybe i should ask this in magpie github issues instead?

Yes. JL already tries to be topmost. Even if JL were to try to keep itself topmost _always_ with some ugly hack, it still wouldn't work in this case, because Magpie seems to manipulate cursor position too, so you cannot interact with JL correctly even if JL is visible.

See: https://github.com/Blinue/Magpie/issues/16

**Comment by rampaa** [comment]
> Even if JL were to try to keep itself topmost always with some ugly hack, it still wouldn't work in this case

It turns out I was wrong. If JL keeps itself as the topmost window with an ugly hack, it can be used with Magpie. I will be adding an option for this in the next version of JL.

**Comment by yourmom2002** [comment]
Nice! Thanks.
