### ISSUE TITLE
Add reading to Custom Dictionary automatically

### ISSUE THREAD

**Issue by AsuraAce** [rampaa/JL#25]
Reading should be added automatically when adding from a dictionary entry to a custom dictionary.

**Comment by rampaa** [comment]
What's the use case for this? Adding new words/names should be normally done when dictionaries you have don't have a matching entry for it at all, or don't have the reading you need. So filling the reading field seems counterproductive.

If you're adding existing entries with your own definitions, I'd advice against it, specifically for verbs. Because verb deconjugation depends on the word class (see [Deconjugation Support](https://github.com/rampaa/JL/blob/master/Deconjugation%20Support.md)) and as you might have noticed, when you add custom words, JL only asks you what type of word it is (e.g. verb) and not its word class (e.g. v5-r). So when you add a verb, JL assumes it can be any verb type and this causes deconjugation process info to be rubbish, that's why the deconjugation process info is not displayed for custom word dictionary entries.

(I could add an additional field to "Add Custom Word" window so that the user can specify the specific word classes/PoS so this wouldn't be a problem. But I'm not sure if there's a demand for it and if users would be able to correctly specify it for words not found in their dictionaries.)

**Comment by AsuraAce** [comment]
what i like/tend to do is the following:

a) when i start a new VN i add new Character names to the Custom Name Dictionary, this way i don´t have to look through a dozen names every time to find the right one. (A lot of Characters are introduced in the beginning so it´s a harder to remember all them).

b) basically same as above but with characters that don´t appear / are not mentioned that often.


since i have a higher priority for the custom name dictionary, the name i´m actually looking for will basically always be the first entry whenever i have to lookup the name. 

filling in the reading myself seems to be less effort but "auto filled readings" will allow for a mouse only workflow.

**Comment by rampaa** [comment]
This has been implemented for "Add Custom Name" window in https://github.com/rampaa/JL/commit/0ff0e31f8580dc994096d3e7433a4362ac77b61f, it will be included in the next release.

> I could add an additional field to "Add Custom Word" window so that the user can specify the specific word classes/PoS so this wouldn't be a problem

This has been implemented as well: https://github.com/rampaa/JL/commit/e6cc5917eec8f6bb1dd84d65c04219a89da980f5
