### ISSUE TITLE
VPN will prevent updates, dictionary downloads and audio playback

### ISSUE THREAD

**Issue by AsuraAce** [rampaa/JL#33]
VPN will prevent updates, dictionary downloads and audio playback **even if i split-tunnel JL**

**Comment by rampaa** [comment]
Tried with Windscribe but cannot reproduce the problem.

What OS and VPN do you use? What is the exact error you get when you try to do those things? Can you send me the relevant log file (it should be located in "...\JL\Logs")?

**Comment by AsuraAce** [comment]
Using Win11 & NordVPN.

[log20230129.txt](https://github.com/rampaa/JL/files/10529428/log20230129.txt)

**Comment by rampaa** [comment]
I neither use Windows 11 nor NordVPN and NordVPN does not seem to have a free trial.

Can other programs (excluding the browsers) check for updates and do things that require Internet connection when you use NordVPN?

Can you install [Windscribe](https://windscribe.com/) just to see if you get the same error while you use it? If you do not get the same error, then it should mean the problem is related to VPN you use. If you do get the same error, then the problem is related to your system configuration (your OS, firewall settings, proxy settings etc.)

**Comment by AsuraAce** [comment]
was able to figure it out. the problem is caused by nordvpn´s split-tunnel feature. if i enable it breaks things and JL won´t be able to connect to the internet it seems (doesn´t matter whether i include in the list of programs that should be ignored by nord or not).

so i basically have to disable split-tunneling in nordvpn in order to use JL properly, which is not ideal but related to nord and not JL. will change my vpn provider soon anyway, until then i will just use this workaround for my reading sessions.
