### ISSUE TITLE
Support for JPDB Mining

### ISSUE THREAD

**Issue by AsuraAce** [rampaa/JL#34]
would be awesome if you could add support for JPDB, if possible.

**Comment by rampaa** [comment]
Explicit JPDB support likely won't be implemented. Though [JPDB-connect](https://github.com/kampffrosch94/jpdb-connect/) seems to [plan to add JL support](https://github.com/kampffrosch94/jpdb-connect/issues/3#issue-1338285329).

**Comment by AsuraAce** [comment]
sounds good, thank you.

**Comment by kampffrosch94** [comment]
So I just started working on this and noticed that it already works without changes 😄 
it probably has been working for half a year already
What was a bit finicky was setting up JL to send to a port other than the default. I don't know if I was too dumb to do it properly but setting JL to send to port 3030 and then hitting refresh resulted in an error with a fresh setup.
I then changed jpdb-connect to listen to the default JL port, did the initial card setup that way and was able to change the port back after.

**Comment by rampaa** [comment]
> it already works without changes 

That's great to hear!

> setting JL to send to port 3030 and then hitting refresh resulted in an error with a fresh setup

Preferences aren't validated and applied until you hit the "Save" button. So when you change the "AnkiConnect server address" and hit the refresh button, it will not use the newly entered address since it hasn't been validated and saved yet. I guess this is nonintuitive and an oversight on my part. I will try to improve this in the version of JL.
