### ISSUE TITLE
Sources of definitions / filter by source - Missing function ?

### ISSUE THREAD

**Issue by Bredan80** [rampaa/JL#35]
**EDIT : I've found the answer to my own question : it's indeed the popup in mining mode. As I'm not mining (as in creating cards for Anki if I got it well), it didn't occur to me to enter mining mode and so I totally missed this function. Sorry for the bother.**

First : thanks for you work, I discovered JL a few days ago and I'm using it since then.

I was reading another issue (https://github.com/rampaa/JL/issues/31) where I saw the screenshot posted by the user.

I see in the upper part of the popup what seem to be a list of the used dictionaries : I can only suppose that that shows the sources of the definitions currently displayed and allows one to filter as well (clicking on one dict would show only the entries belonging to that dict etc.).

I don't understand why, but I've no such functionality and I would love to. My only guess is that it could be linked to Anki integration, as to my knowledge it's the only function I'm not using. Can someone enlighten me ?

**Comment by rampaa** [comment]
It's a little bit late but let me explain the situation. "Mining Mode" is kind of a misnomer, it's not used solely for mining, you need to be in mining mode to interact with the popup.  "Left click/Touch" and "Text select" lookup modes will open the popup in mining mode from the get go. You only need to enable the mining mode when you use the "Mouse move" lookup mode.

Also you can filter results by other dictionaries without activating the mining mode with the next/previous dictionary hotkeys (page down/up by default) but since all results are not generated when mining mode is not activated, you will get a incomplete list of results.
