### ISSUE TITLE
Selected Dictionary Tabs should be remembered

### ISSUE THREAD

**Issue by AsuraAce** [rampaa/JL#38]
the selected dictionary tab should be remembered instead of resetting to `all` dictionaries.

- saves clicks. want to use/prioritize a certain dictionary (for example going mono for a session, or going with a dictionary that has example sentences and so on)

![image](https://user-images.githubusercontent.com/13394741/215076793-f9a3ddc8-fdbe-45ee-93fc-cae83a760bb6.png)

**Comment by rampaa** [comment]
You can prioritize dictionaries through "Manage Dictionaries". First dictionary has the highest priority and the last one has the least. Longer/Exact matches will have more priority regardless of the dictionary priority but that's the intended behavior.

You can also select which dictionary results are shown under the "All" tab. If you don't want to see, say, JMnedict results under "All", you can enable the "Don't show results under All" option through  "Manage Dictionaries->JMnedict->Edit".

**Comment by AsuraAce** [comment]
Thank´s i´m aware that i can sort and hide the results. Would be too much effort to change for every other session or within a session. 

Remembering the last selected dictionary on the other hand, would allow the user to change dictionaries with a single click within a reading session.

**Comment by rampaa** [comment]
Suppose that you've chosen a specific dictionary and JL remembered that choice, what would you expect to happen if a word you tried look up has no matching entry in that dictionary but other dictionaries actually do have matching entries? Should JL act as if there's no result? Should it fall back to "All" tab?

If it doesn't fall back, you get no result for that entry and that seems pretty useless. It's pretty much the same thing as deactivating all the other dictionaries.

If it falls back, then you are no longer guaranteed to get the results from the dictionary you've selected, which is pretty much the same thing as trying to sort dictionaries by their priorities. (Also should "All" remembered as the last selected tab in case of a fall back?)

Also just because someone wanted to check out JMnedict results, wouldn't necessarily mean that they would want JMnedict to be their default tab for that session. So either I'd have to come up with a way to distinguish selected tab and remembered tab, or the user would need to select the tab they want to be remembered after checking out other tabs, which means more clicks. 

Also there's the matter of whether this "remembered" dictionary should be remembered for that session or permanently, or should JL allow a different tab than "All" to be the default tab while also allowing the user to temporarily override it for that session.

**Comment by AsuraAce** [comment]
- fall back to "All" makes sense.
- "fall back All" should not be remembered as last selected.
- more clicks in this situations, yes but better workflow (alternatively make this behavior optional)
- i don´t think it makes much of a difference. permanently remembering seems preferable imo.
- allowing another tab to be used as default sounds like a nice addition (if it´s easy to implement)

**Comment by rampaa** [comment]
> * fall back to "All" makes sense.

Suppose that you try to look up 姉君, but the remembered dictionary has only an entry for 姉 while another dictionary has also an entry for 姉君. Should JL fall back to "All" tab for cases where other dictionaries have longer matches, in this case 姉君? If it doesn't fall back to "All" tab, you're probably missing out the word you were trying to look up, and instead only see a definition for 姉. On the other hand, if it falls back to "All" tab for those cases too, then you get pretty much the exact same behavior of current JL.

**Comment by AsuraAce** [comment]
yes it should fall back to "All"

**Comment by rampaa** [comment]
> yes it should fall back to "All"

If JL falls back to "All" tab for those cases too, then you get pretty much the exact same behavior of current JL. I don't think this feature is worth the effort.
