### ISSUE TITLE
Dictionary Tabs should behave like browser tabs

### ISSUE THREAD

**Issue by AsuraAce** [rampaa/JL#39]
dictionary tabs should have a dynamic width and should stay on the same row at all times, if possible.

- cleaner more organized look. visual hierarchy and makes it easier to focus on the important parts

![image](https://user-images.githubusercontent.com/13394741/215077044-512f8a76-7bf7-4b5d-a5fc-2a0256fd2fb9.png)

**Comment by rampaa** [comment]
This should be less of a problem in the next version of JL thanks to https://github.com/rampaa/JL/commit/b5fef5b1db19431fd4f97218a5f534d7364594b1. Also try using shorter names (e.g. "CWD" instead of "Custom Word Dictionary").

I will have a look at this when I have the time but chances are implementing this won't worth the effort.

**Comment by AsuraAce** [comment]
i agree, hiding dicts without result and renaming should have same effect (have all of them on one line).
