### ISSUE TITLE
Crash while managing dictionaries

### ISSUE THREAD

**Issue by Bredan80** [rampaa/JL#42]
Hello.

I've added a few Yomichan/EPWING dicts : here is the list.

![Capture](https://user-images.githubusercontent.com/121174359/215639940-c19b92e3-fed5-4482-afad-c1ef106b3de5.png)

This is probably not exhaustive as I've not tested every combinations, but in this setup I can reproduce the crash (systematically) by trying to move up Daijirin or Daijisen. I can move them as I want as long as I won't try to move them to the 5th position and up from the bottom (position occupied by JMDICT here). Of course, I've tried to remove them and add them up but the crashes occurred again. 

As every dict (including Daijirin and Daijisen) are functional nevertheless, I'm using it in this state.

**Comment by rampaa** [comment]
Thanks for the log/dicts file, the issue will be fixed in the next version of JL.

> I'm getting the warning message [WRN] CopyFromClipboard failed repeated ad nauseam, but JL seems to work properly

You can basically ignore that warning. If there's a text in clipboard but JL cannot grab it because the clipboard is blocked in that moment for whatever reason, the aforementioned warning is logged and JL re-tries to get the text until it either succeeds or until clipboard has no text.

> One of the log (from a previous day) is so full of this warning that the file for this day is 1Gb large... whatever the reason, there should be a limit ^^.

That's quite bizarre. I'd like to see the file if possible. The biggest log file I got from JL is around 4 MiB. If you are saying "CopyFromClipboard failed" is the sole culprit here, I can just not log that warning I guess.

**Comment by rampaa** [comment]
Should be fixed by https://github.com/rampaa/JL/commit/32aacd8f8e263a6b68efdb6c0b399f79a7874036, https://github.com/rampaa/JL/commit/e67060519f840739481392a3ed65b59fad5e326d and https://github.com/rampaa/JL/commit/f8e3ef2ebf2dbfc9cfbdc71bd0276dcfef148b13.
