### ISSUE TITLE
Listen to hotkeys on an API endpoint / Add pause button

### ISSUE THREAD

**Issue by forsakeninfinity** [rampaa/JL#53]
The only real hiccup I have with JL atm is around not being able to use hotkeys when it doesn't have focus. Using it with magpie requires that it not be focusable, but not being able to use hotkeys means I can't pause listening to websockets for example which ruins the experience when reading VNs as there can be a flow of previously seen text over the stream that pollutes the output in JL when I am just trying to read the log. This seems relatively easy to work around if JL starts a webserver to listen to hotkey input (a REST endpoint that takes in a simple JSON blob for example) that could then be invoked by autohotkey or some other software that don't require focus.

Something like the above might be nice to enable using hotkeys in general, but my primary want is to be able to pause getting text so having a button that can be clicked to invoke pausing / resuming reading text from sources without taking the focus away (I assume this is possible given that mouse click based lookup and mining is possible) would also be very helpful on its own.

**Comment by rampaa** [comment]
> Using it with magpie requires that it not be focusable

If you are using the "Mouse move" lookup mode, disabling the "Focusable" option is actually optional (while disabling the "Preferences>Main Window>Focus on hover" and "Preferences>Popup>Focus on lookup" options is required). If you enable the "Focusable" option you still can look up words without JL getting the focus. It will only get the focus on mouse clicks (I _may_ be able special case middle button clicks so that they don't cause JL to get the focus even if "Focusable" is set to true). You can leverage this fact to make JL get the focus with the left mouse click and use the related hotkey afterwards. If you are not using the "Mouse move" lookup mode though, this is a moot point.

> but not being able to use hotkeys means I can't pause listening to websockets

You can always disable/enable it through "Preferences->Main Window->Enable WebSocket text capture".
Also if you are using Textractor to get the text, you can use its "pause button" before skipping any text etc. See: https://github.com/Artikash/Textractor/pull/847, https://github.com/Artikash/Textractor/issues/868#issuecomment-1492428212

> pollutes the output in JL when I am just trying to read the log

If you only care about reading the backlog, using JL's internal backlog would mitigate this. Though if you also want to re-listen to some voices etc. it is a moot point, again.   

> a webserver to listen to hotkey input (a REST endpoint that takes in a simple JSON blob for example) that could then be invoked by autohotkey or some other software that don't require focus

Sounds like global hotkey support with extra steps. The last time I've pondered over adding global hotkey support, I've decided against it. I guess I will ponder over it a little bit more.

> my primary want is to be able to pause getting text so having a button that can be clicked to invoke pausing / resuming reading text from sources without taking the focus away (I assume this is possible given that mouse click based lookup and mining is possible) 

This should indeed be possible. But the problem is I don't want to bloat JL's main window by adding another button to it, I want it to stay as minimalistic as possible so I am not sure if I am okay with adding a button like that.

**Comment by forsakeninfinity** [comment]
> If you are using the "Mouse move" lookup mode,

I use the mouse click lookup mode. Mouse move feels too spastic for me.

>  if you are using Textractor to get the text, you can use its "pause button" before skipping any text et

I don't want to tab out to textractor (which breaks immersion and makes magpie get an aneurysm). It's kind of the selling point of JL that I don't have to leave the game window I guess.

> Sounds like global hotkey support with extra steps.

Indeed. I wasn't sure if you had any reasons to not have global hotkeys. I was thinking that it would take the responsibility (for security concerns or w/e) off you and let the user customize however they want, e.g., potentially they could script together multiple actions with one hotkey if there was API support for the options I guess. But just global hotkeys (even if only for a subset) would be great.

> If you only care about reading the backlog, using JL's internal backlog would mitigate this. Though if you also want to re-listen to some voices etc. it is a moot point, again.

Yeah I want to re-listen to voices for mining etc. Also, without focus, the input to JL for scrolling backlog also gets sent to the game which can fuck it up depending on the game.

> I want it to stay as minimalistic as possible so I am not sure if I am okay with adding a button like that.

JL is honestly perfect for me other than this one issue. I would prefer a hotkey over a button too fwiw. 

Thanks for the quick response btw. Much appreciated.

**Comment by rampaa** [comment]
Implemented global hotkey support in https://github.com/rampaa/JL/commit/804e8d9f7bb8b37490d82be72e23b12c523e43e3.

Only hotkeys with modifiers (e.g. Ctrl+T), function keys (except for F12) and numpad keys can be used as global hotkeys. E.g., You cannot use M as a global hotkey, but you can use Ctrl+Alt+M as one.

**Comment by forsakeninfinity** [comment]
Thanks a ton for the very quick runaround on this. Much love and respect.
