### ISSUE TITLE
Adding Furigana to dictionary definitions

### ISSUE THREAD

**Issue by Saynarisal123** [rampaa/JL#54]
It would be ideal if the definition pop-up contained Furigana above the word being looked-up, as it helps associating a given kanji with its reading, in the same manner that Yomichan handles definitions.
Thank you for your amazing work, this software is a game changer in VN reading.

**Comment by rampaa** [comment]
Unfortunately WPF does not have proper ruby text support. (https://github.com/dotnet/wpf/issues/7595) So I don't think I can implement this (efficiently). So unless WPF gets proper ruby support or someone has a really good idea as to how implement this, it will not be implemented.

Note that even if it were to be implement, the JL version of this feature would look like Yomichan with `Result grouping mode` set to `Group related terms`, e.g.:
![image](https://github.com/rampaa/JL/assets/25622653/efdac951-7ed8-4a81-805d-267aa3b752eb)

**Comment by Saynarisal123** [comment]
Is `Group related terms` a variable that can be set to false, or at least tweaked in a way that would render results in a similar fashion to Yomichan?
Given the inadequacy of the WPF, for displaying Ruby text support, is there better framework, that's better suited for making JL perform in a similar manner to Yomichan?

**Comment by rampaa** [comment]
> at least tweaked in a way that would render results in a similar fashion to Yomichan?

Kinda. There's no `Group related terms` option in JL (and likely won't be in the future either), so you cannot set it to `No grouping`. Built-in JMdict, JMnedict and dictionaries created by Nazeka EPWING Converter will have results similar to Yomichan with `Result grouping mode` set to `Group related terms`. But, this is not the case for Yomichan dictionaries (i.e., Dictionaries that can be found at https://foosoft.net/projects/yomichan/ and dictionaries created by Yomichan Import) because the Yomichan dictionary format is incapable of specifying alternative spellings and multiple readings for a single entry. So those dictionaries will have results similar to Yomichan with `Result grouping mode` set to `No grouping`.

> Given the inadequacy of the WPF, for displaying Ruby text support, is there a better framework, that's better suited for making JL perform in a similar manner to Yomichan?

I've considered Avalonia before (since it's cross-platform and whatnot) but it doesn't have ruby text support either (https://github.com/AvaloniaUI/Avalonia/issues/10556) and it lacks some essential features that blocks JL being ported over to it (see: https://github.com/AvaloniaUI/Avalonia/issues/9540). WinUI doesn't have ruby text support either (https://github.com/microsoft/microsoft-ui-xaml/issues/1789). Even Qt doesn't seem to support ruby text. So no, I am not really aware of a good alternative. It seems like I'd need to use something like WebView2 but I'd prefer not having this feature rather than using something like WebView2/QtWebEngine etc.

Also, even if there was such a GUI framework, it would mean rewriting the whole JL.Windows from scratch. Which is a _huge_ work.

**Comment by Saynarisal123** [comment]
> I've considered Avalonia before (since it's cross-platform and whatnot) but it doesn't have ruby text support either

Flutter seems to be able to support Ruby text (or at least a variation of Furigana supporting font) as Jidoujishou by Irorpilla (available on this site), seems to be able to display said characters easily, the problem is that JL will have to be completely rewritten. 
Flutter is multi-platform so a desktop application is possible to make but as I said it'll most likely require a complete rewrite. 

>  the Yomichan dictionary format is incapable of specifying alternative spellings and multiple readings for a single entry.

Is there any feasible modification to file-format/dictionary logic that can enable `Group term-reading pairs`? 
I don't know if it's possible to copy the way Yomichan handles term-reading pairs but, there has to be a component in the extension whose function is to group terms based on pairs, such as a custom list or something of the sort.

**Comment by rampaa** [comment]
A complete rewrite of JL in another language is not likely. WPF likely won't add ruby text support anytime soon either. Plus, adding furigana and removing the readings section wouldn't work well with how JL shows the pitch accent for those readings either. Unless something changes about the aforementioned facts, this feature will not be implemented.
