### ISSUE TITLE
issue opening the exe using a batch file

### ISSUE THREAD

**Issue by JunkyardCat** [rampaa/JL#62]
So when i opened the exe with a batch file it changed the config directory of the dictionary and custom txt to the place where the batch file is located. So was wondering if theres a way to not change anything when run using a batch file (.bat). This is the only config i am aware, not sure if there is other changes when doing it this way.  

Reason why im using a batch file is to that i dont have to go inside each of the tools like textractor the games and jl.

**Comment by rampaa** [comment]
Fixed by https://github.com/rampaa/JL/commit/b27b56a03baceea5e5ed6c8047ff3b273b2c6dcf and https://github.com/rampaa/JL/commit/33631c21435c29aa422384500e314dce968a28e3. The fix will be included in the next version of JL.

Note that instead of running JL like `START C:\Users\User\Desktop\JL.exe` running it like `START /D C:\Users\User\Desktop\JL C:\Users\User\Desktop\JL\JL.exe` would also solve the problem.
