### ISSUE TITLE
Crashes after downloading latest version of JMDict

### ISSUE THREAD

**Issue by Chappydev** [rampaa/JL#80]
Tried with both x86 and x64 versions. 

After downloading all the dictionaries from the prompts including JMDict, it asks me to download the latest version of JMDict. If I click yes, it apparently downloads it, and then a few seconds after it alerts me that the download is complete, the app freezes briefly and then crashes. 

If I say no to downloading the latest version, it doesn't appear to crash, but it prompts me again the next time I launch the app to download jmdict and then once again prompts me to download the latest version.

**Comment by PoshestPoro** [comment]
I have the same problem, it seems to be installing it fine though.

**Comment by rampaa** [comment]
The issue is fixed by https://github.com/rampaa/JL/commit/6aa1497b147131486ea30c25dac6a3aa0bbd5328. The fix will be included in the next version of JL. Since it's not decided when the next version of JL will come out, you can use the following JMdict file in the meanwhile: https://www.mediafire.com/file/fdrxqk1j4k3o6qv/JMdict.xml/file
