### ISSUE TITLE
Would it be possible to implement frequency harmonic mean or something similar.

### ISSUE THREAD

**Issue by PoshestPoro** [rampaa/JL#81]
Similar to how jp-mining-note handle bars do it on yomitan, I believe it uses a harmonic mean by default. 

https://github.com/MarvNC/JP-Resources
I believe it is in this github repo under freq handlebars.

This is very useful in conjunction with the reorder anki addon as you can use this to sort your anki cards by frequency.

**Comment by PoshestPoro** [comment]
private static int FrequencySortHarmonic(JLField rawFreq)
    {
        int[] rawFreqArray = int32.Parse(rawFreq.Split(", "));
        int harmonicMean = -1; // Default
        int temp = 0;


        foreach(freq in rawFreqArray)
        {
            temp += (1/freq);
        }

        harmonicMean = rawFreq.Sum() / temp;
    }
Implementation could maybe go something along these lines.

**Comment by PoshestPoro** [comment]
Maybe you could use a weighted harmonic mean of some sort, though I think the point of using a harmonic mean is to remove these deviations from the final result. It would probably be best to ignore frequency dictionaries that don't give any frequency data for the word you mined. 
A preferred frequency could also work. Maybe you could implement something where it compares the preferred frequency to other frequency dictionaries and see if it deviates a large amount from the others and account for that in some way, maybe by using a backup preferred dictionary if necessary.

**Comment by rampaa** [comment]
I don't think harmonic mean can solve either of the problems I've described. It can't possibly solve the problem of having some dictionaries where a greater number means the term is more frequent, while in other dictionaries the reverse is true. I would need to normalize those dictionaries somehow. And I don't think it can solve the problem of some dictionaries working with significantly different ranges than other dictionaries (though I might be wrong about this).

I can make it so that preferred frequency will be the first available frequency info from the frequency dictionaries, i.e., if the frequency dictionary with the highest priority have the relevant info that will be used, if it doesn't the frequency dictionary with the second highest priority will be used and so on. If none of them has the frequency data for the term int.MaxValue can be returned. But this approach has the same problems that harmonic mean would have, so meh.

Returning the frequency value from the frequency dictionary with the highest priority without any fallback is the option that makes most sense to me. If you don't like it and still want to have a field for (harmonic) average, I guess I can implement that instead.

**Comment by PoshestPoro** [comment]
In that case, I think your implementation you suggested would work best. With a potentially new field that returns the highest ranked list in your frequency dictionaries, otherwise return int.MaxValue.

**Comment by rampaa** [comment]
Added `Preferred Frequency` (no fallback) and (Harmonic) `Average Frequency` fields.

If a greater number means the term is more frequent that value will be normalized by subtracting it from int.MaxValue (might subtract it from the max frequency value of that dictionary in the future but that's more expensive) while calculating the `Average Frequency`.

Also in case of there being no frequency info for the term I decided to not return anything instead of returning int.MaxValue as that's more in-line with how the existing `Frequencies` and `Raw Frequencies` fields behave.
