### ISSUE TITLE
Export Multiple Definitions to Anki

### ISSUE THREAD

**Issue by ccos89** [rampaa/JL#84]
Hi, this program is incredible and I'm only sad it's taken me this long to find it.  The only thing I wish the program was capable of is exporting multiple definitions to cards, as I often like having a monolingual definition or monolingual explanation of a phrase (eg 俗語辞書) but also a bilingual definition for quick reference when repping in Anki.  Is there any way this functionality could be added?

Without a lot of coding expertise and without diving into the code, I'm visualizing this being possible in a couple ways - one, a Ctrl+Click/Ctrl+Arrow/Ctrl+Corresponding Number Key corresponding to an integer assigned each dictionary return in the popup dictionary allowing for multiple dictionaries to be selected before confirming the mining operation, which exports all selected definitions to the current 'Definitions' mappable field. 

Two, an integer could be assigned to each dictionary in the dictionary list (as currently is) and then in the mapping fields for exporting definitions, instead of a single 'Definitions' option there could be a 'Current Definition' which would have the same functionality as the current 'Definitions does'.  In addition, there could also be mappable fields for 'Dictionary 1,' 'Dictionary 2,' and so forth that would correspond to the assigned number in the manage dictionaries screen.  The user could then have an Anki note type where there are multiple definition fields ('Definition 1,' 'Definition 2,' etc.) which could be mapped to correspond to the desired dictionaries. 

Of course this will sometimes result in undesired definitions being added to the card and somewhat bloated cards in general but this method is how I've gotten around being able to export multiple definitions from KOReader to Anki and by collapsing all definitions except the current selected definition it allows the ability to quickly reference the best definition while having the others readily available for additional reference when learning the card for the first time or during a lapse, etc.

I've included a picture below of how I've formatted my cards I use for KOReader exports to help visualize what I mean:

![anki card example](https://github.com/rampaa/JL/assets/133320139/a786758d-61e2-462f-8a9d-d4131fba2d90)

Anyway, just some ideas of how it might work.  I really appreciate your work on the project and hope this works out!  Even though I think I use more definitions on my cards than many do I know a lot of people want to be able to export multiple definitions with mining tools for help with the monolingual transition, etc.

**Comment by rampaa** [comment]
How would you expect such a functionality to work exactly? Let's say you want to mine 魂, in JMdict there's a single entry for it with 3 readings namely たましい, だましい and たま. Yomichan dictionaries never have more than one reading per entry, so there will never be a 1:1 primary spelling-reading match for those kind of entries. Would you expect to be able to select definitions from arbitrary dictionary entries even when their readings/primary spelling/word kind etc. do not match exactly and have them included as a part of the mined entry's definition?

If I were to implement this functionality I'd probably add a checkbox for the definitions per entry that can be selected. But I am not really convinced that I should implement this functionality because meshing different definitions from lots of dictionaries to a single Anki card doesn't strike me as a terribly good idea. For the most part, I'd expect the user can understand the meaning of a term by reading the definitions of it from a single dictionary. In the off chance that every single dictionary has sub-optimal definitions for a term, I'd expect the user to edit the definitions field of the created Anki card manually so that it will be more palatable for the user. For the 99% of the cases, I don't see the benefit of meshing definitions from different dictionaries.

**Comment by rampaa** [comment]
Due to aforementioned reasons I will not implement this feature as requested. Thanks to https://github.com/rampaa/JL/commit/fba430634e2838e725739177e42b6df045c571cd, you can make definitions text box editable and edit it as you please before mining. Hopefully that much granularity will be helpful for your use-case as well.

**Comment by rampaa** [comment]
This is now implemented by https://github.com/rampaa/JL/commit/cab9d4cab84690728302f3c6c6677b1b7d54408f. `Definitions from Multiple Dictionaries` will get the definitions from same dictionary categories, e.g., if you are mining a word from a word dictionary like `JMdict`, only the definitions of word dictionaries (i.e., `JMdict`, `Custom Word Dictionary`, `Word Dictionary (Yomichan)` and `Word Dictionary (Nazeka)`). Same goes for other dictinoary categories, if you mine a term from a name/kanji/other dictionary, only the definitions from dictionaries with the same category will be selected. For a definition to be included, its `Primary Spelling` and `Selected Reading` must match.
