### ISSUE TITLE
Anki mining - Image not working

### ISSUE THREAD

**Issue by Higurashi-z** [rampaa/JL#90]
I'm trying to mine words to anki and saw that there was a field for image. All the other fields that I have tried worked fine, but I'm not sure how to make it mine the picture (I assume that this is what this field was supposed to do). I have checked the "info" button but there's no information about this field. Every time that I tried it comes back empty on anki.

![image](https://github.com/rampaa/JL/assets/172344900/d835a875-d03c-4fb5-858b-6c041d2e868d)
![image](https://github.com/rampaa/JL/assets/172344900/97b75b47-ac4b-43db-b8ff-e95521ef9fdb)

**Comment by rampaa** [comment]
JL will grab the image from the clipboard if it contains an image. Copy the image to clipboard (with PrintScreen key etc.) before mining the term and it should work as expected. I probably should have explained this in the info dialog instead of only mentioning it in a release note (https://github.com/rampaa/JL/releases/tag/1.18.0).
