### ISSUE TITLE
Non-adjacent text with Selected Definitions

### ISSUE THREAD

**Issue by Higurashi-z** [rampaa/JL#91]
About anki mining, there's the option on fields of "selected definitions". It looks pretty useful, but I think that would be interesting if there was a way to select non-adjacent text, similar to how it's done on Microsoft word, where you can just hold the ctrl key and selected multiple text even if they aren't beside each other. Sometimes if you're using a monolingual dictionary definitions can be too long, but there's multiple information that you want, but they aren't beside each other. So, if we had a way to select non-adjacent words would be very useful.

**Comment by rampaa** [comment]
WPF TextBox does not support that behavior. It seems like it's possible to simulate that behavior with a RichTextBox (https://stackoverflow.com/a/2853666) but I've tested using the RichTextBox control instead of the TextBox control in the past and it turned out that RichTextBox is too resource hungry to be useful as a TextBox replacement. So I can't realistically implement this feature, sorry.

**Comment by rampaa** [comment]
I've thought about this a little bit more. Although I cannot implement the requested feature (i.e., non-adjacent text selection) I can allow you to edit the definition textbox directly, which would allow you to temporarily delete the parts you don't want to mine.
