### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Omar-Abdul-Azeez** [rampaa/JL#92]
[log20240612.txt](https://github.com/user-attachments/files/15795573/log20240612.txt)

**Comment by rampaa** [comment]
1) Did this happen on a fresh JL setup or did it happen after an update?
i. If it happened after an update, did you create different different profiles?

2) Can you share Configs.sqlite file placed under ..\JL\Config?

3) What OS do you use?

4) Can you try delete Configs.sqlite (and Configs.sqlite-journal if it exists) and re-run JL, does JL crash again?

**Comment by Omar-Abdul-Azeez** [comment]
It turns out to have been a frozen instance was left open (which by the way has no open window to tell from) which crashed the next opened instance.
It was on a freah install on windows. I think it's working fine now.

**Comment by Roeekush** [comment]
I also had a problem where JL would crash on startup. But there was no frozen instance as far as I can tell.
 Deleting Configs.sqlite and jounral fixed it.
Not a fresh install, worked fine day before
I use windows 11

https://drive.google.com/drive/folders/1jkMZqIifpeetcwUAyRUCHvLp1wvs7wpB?usp=drive_link here are the files if you do want to do some investigating.

**Comment by rampaa** [comment]
I am not sure how it happened but the presence `Configs.sqlite-journal` file indicates that JL was unexpectedly closed before it could successfully save all your configs. This might be due to an unhandled exception that caused JL to crash (if you have any prior log file that indicate a different exception that caused JL to crash, please do share it), forcefully terminating JL through task manager with an extremely unlucky timing etc.

Anyway, I will make it so that starting from the next version of JL, your configs will be gracefully rolled back to their last recoverable state.

**Comment by Roeekush** [comment]
Thanks for the quick reply!

I added a log file from the day before to google drive. It seems like there was an error loading some yomichan dictionary that might have crashed it? Never had this problem before.

**Comment by rampaa** [comment]
That shouldn't case JL to crash. It will just delete it from the `dicts.json` file. If you can find out the missing dictionary that couldn't be imported I can have a look at it as well.

**Comment by Roeekush** [comment]
I just noticed the error wasn't  from a day ago, it was from a month and a ago, my bad

no idea what caused this bug
