### ISSUE TITLE
how to specify AnkiConnect server address ?

### ISSUE THREAD

**Issue by thangld201** [rampaa/JL#98]
Hi @rampaa, integration with Anki requires setting up AnkiConnect server address. how could I do this ? I do find such entries in Anki Desktop Preferences ...

**Comment by rampaa** [comment]
Preferences->Anki
![image](https://github.com/user-attachments/assets/0395e255-a98d-45db-ab68-c14e7e00a450)

**Comment by thangld201** [comment]
@rampaa, I got `Communication error ! Is Anki open?` though I turn on the Anki Desktop App ... Do you think the server address is different (e.g. not 127.0.0.1:8765) ?

**Comment by rampaa** [comment]
You need to be in mining mode in order to mine words. "Left click/Touch" and "Text select" lookup modes will automatically activate the mining mode. If you are using the "Mouse move" lookup mode, you can activate the mining mode with a middle mouse click or with the mining mode hotkey. When you enable the mining mode, you should see a message showing you how to mine a word like:

![image](https://github.com/user-attachments/assets/30ff9568-d6a6-4e90-a355-430c43463b84)

In this case you need to press the orange-colored 妹 character.

You can also use your keyboard to mine words, if you prefer that, see the following hotkeys:

![image](https://github.com/user-attachments/assets/3e130678-633b-4ee3-9697-03d2642cb1c3)
